sudo: required
services:
  - docker

before_install:
  - docker build -t wilmer737/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wilmer737/react-test npm test --  --coverage

after_success:
  - docker build -t wilmer737/multi-client ./client
  - docker build -t wilmer737/multi-nginx ./nginx
  - docker build -t wilmer737/multi-server ./server
  - docker build -t wilmer737/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DH_PASSWORD" | docker login -u "$DH_USER" --password-stdin
  # Push to DockerHub
  - docker push wilmer737/multi-client
  - docker push wilmer737/multi-nginx
  - docker push wilmer737/multi-server
  - docker push wilmer737/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-467654544545
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
