sudo: required
services:
  - docker

before_install:
  - docker build -t wilmer737/react-test -f ./client/Dockerfile.dev .

script:
  - docker wilmer737/react-test npm test --  --coverage

after_success:
  - docker build -t wilmer737/multi-client ./client
  - docker build -t wilmer737/multi-nginx ./nginx
  - docker build -t wilmer737/multi-server ./server
  - docker build -t wilmer737/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DH_PASSWORD" | docker login -u "$DH_USER" --password-stdin
  # Push to DockerHub
  - docker push wilmer737/multi-client
  - docker push wilmer737/multi-nginx
  - docker push wilmer737/multi-server
  - docker push wilmer737/multi-worker

  